name: Build Distributions

on:
  push:
    tags:
      - 'v*' # Triggers on versioned tags like v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Linux JAR and DEB
        run: ./gradlew packageUberJarForCurrentOS packageDebDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            build/compose/jars/*.jar
            build/compose/binaries/main/deb/*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Windows MSI
        run: ./gradlew packageMsiDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/compose/binaries/main/msi/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build macOS DMG
        run: ./gradlew packageDmgDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: build/compose/binaries/main/dmg/*.dmg
