name: Build Smart Attendance Desktop Clients

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Desktop-Clients
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Linux
        run: ./gradlew packageUberJarForCurrentOS packageDebDistribution
      - uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            Desktop-Clients/build/compose/jars/*.jar
            Desktop-Clients/build/compose/binaries/main/deb/*.deb

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Desktop-Clients
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Windows
        run: ./gradlew packageMsiDistribution
      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: Desktop-Clients/build/compose/binaries/main/msi/*.msi

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Desktop-Clients
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build macOS
        run: ./gradlew packageDmgDistribution
      - uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: Desktop-Clients/build/compose/binaries/main/dmg/*.dmg
