name: Build Desktop Distributions

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Desktop-Clients
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Linux
        run: ./gradlew packageUberJarForCurrentOS packageDebDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: linux-desktop
          path: |
            desktop-client/build/compose/jars/*.jar
            desktop-client/build/compose/binaries/main/deb/*.deb

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: desktop-client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Windows
        run: ./gradlew packageMsiDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: windows-desktop
          path: desktop-client/build/compose/binaries/main/msi/*.msi

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: desktop-client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build macOS
        run: ./gradlew packageDmgDistribution
      - uses: actions/upload-artifact@v3
        with:
          name: macos-desktop
          path: desktop-client/build/compose/binaries/main/dmg/*.dmg
